apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  volumes:
    - name: opencode-auth
      secret:
        secretName: opencode-auth
        items:
          - key: auth.json
            path: auth.json
  containers:
    - name: devpod
      resources: {}
      volumeMounts:
        - name: opencode-auth
          mountPath: /home/dev/.local/share/opencode/auth.json
          subPath: auth.json
          readOnly: true
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  restartPolicy: Always
